[workspace]
members = [
    "posts-service",
    "posts-service/migration",
    "users-service",
    "users-service/migration",
    "common",
    "gateway-service",
    "auth-service",
    "notification-service",
    "notification-service/migration",
]
resolver = "2"
